In [2]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

# Polybench Experimental Results

This notebook puts together how we run Polybench experiments using the `pb-flow` script, and how we process the run results to get the formatted table.

## Setup

We need to put the `python/` directory into the `PYTHONPATH`.

In [3]:
import sys
import os
import pandas as pd
import matplotlib.pyplot as plt

sys.path.append(os.path.dirname(os.path.realpath(os.getcwd())))

In [4]:
from pyphism.polybench import pb_flow

In [5]:
len(pb_flow.discover_examples('./example/polybench'))

30

In [6]:
options = {
  "baseline": pb_flow.PbFlowOptions(
    pb_dir=os.path.join(pb_flow.get_project_root(), 'example', 'polybench'),
    work_dir=os.path.join(pb_flow.get_project_root(), 'tmp', 'phism', 'pb-flow.baseline'),
    job=30,
    polymer=False,
    cosim=True,
    dataset='MINI',
    cleanup=False,
    loop_transforms=False,
    improve_pipelining=False,
  ),
}

## Run `pb-flow`

In [7]:
pb_flow.pb_flow_runner(options["baseline"])

>>> Starting 30 jobs (work_dir=/mnt/ccnas2/bdp/rz3515/projects/phism/tmp/phism/pb-flow.baseline) ...
>>> Finished trmm            elapsed: 12.744077 secs   Status: 1  Error: "vitis_hls /mnt/ccnas2/bdp/rz3515/projects/phism/tmp/phism/pb-flow.baseline/linear-algebra/blas/trmm/tbgen.tcl failed."
>>> Finished deriche         elapsed: 13.187082 secs   Status: 1  Error: "vitis_hls /mnt/ccnas2/bdp/rz3515/projects/phism/tmp/phism/pb-flow.baseline/medley/deriche/tbgen.tcl failed."
>>> Finished floyd-warshall  elapsed: 37.871616 secs   Status: 0  Error: "No Error"
>>> Finished nussinov        elapsed: 37.937710 secs   Status: 0  Error: "No Error"
>>> Finished symm            elapsed: 93.664803 secs   Status: 0  Error: "No Error"
>>> Finished doitgen         elapsed: 94.870506 secs   Status: 0  Error: "No Error"
>>> Finished durbin          elapsed: 94.882741 secs   Status: 0  Error: "No Error"
>>> Finished syrk            elapsed: 97.126487 secs   Status: 0  Error: "No Error"
>>> Finished trisolv         elapsed: 102.577879 secs   Status: 0  Error: "No Error"
>>> Finished syr2k           elapsed: 103.927764 secs   Status: 0  Error: "No Error"
>>> Finished jacobi-2d       elapsed: 108.622093 secs   Status: 0  Error: "No Error"
>>> Finished fdtd-2d         elapsed: 109.157218 secs   Status: 0  Error: "No Error"
>>> Finished 3mm             elapsed: 110.627114 secs   Status: 0  Error: "No Error"
>>> Finished mvt             elapsed: 111.246668 secs   Status: 0  Error: "No Error"
>>> Finished gesummv         elapsed: 114.715380 secs   Status: 0  Error: "No Error"
>>> Finished 2mm             elapsed: 132.248457 secs   Status: 0  Error: "No Error"
>>> Finished heat-3d         elapsed: 133.100148 secs   Status: 0  Error: "No Error"
>>> Finished gemm            elapsed: 133.840037 secs   Status: 0  Error: "No Error"
>>> Finished gramschmidt     elapsed: 139.817338 secs   Status: 0  Error: "No Error"
>>> Finished bicg            elapsed: 144.700597 secs   Status: 0  Error: "No Error"
>>> Finished ludcmp          elapsed: 144.719087 secs   Status: 0  Error: "No Error"
>>> Finished covariance      elapsed: 160.157851 secs   Status: 0  Error: "No Error"
>>> Finished lu              elapsed: 170.780202 secs   Status: 0  Error: "No Error"
>>> Finished correlation     elapsed: 244.418857 secs   Status: 0  Error: "No Error"
>>> Finished cholesky        elapsed: 244.442478 secs   Status: 0  Error: "No Error"
>>> Finished atax            elapsed: 385.365107 secs   Status: 0  Error: "No Error"
>>> Finished jacobi-1d       elapsed: 401.067727 secs   Status: 0  Error: "No Error"
>>> Finished adi             elapsed: 590.996017 secs   Status: 0  Error: "No Error"
>>> Finished gemver          elapsed: 1063.473848 secs   Status: 0  Error: "No Error"
>>> Finished seidel-2d       elapsed: 1223.452072 secs   Status: 0  Error: "No Error"
Elapsed time: 1224.671541 sec
>>> Dumping report ...


              name   status latency DSP_usage FF_usage LUT_usage  \
0              2mm  SUCCESS    6830        50     9999      6720
1              3mm  SUCCESS   11113        30     6792      6466
2              adi  SUCCESS   51181        53    18421     13623
3             atax  SUCCESS    1928       595    52231     43267
4             bicg  SUCCESS    2596        39    13630      6473
5         cholesky  SUCCESS  137534        14     1614      2279
6      correlation  SUCCESS   12927        34    12033     10260
7       covariance  SUCCESS   13455        28    10179      6731
8          deriche  SUCCESS    None      None     None      None
9          doitgen  SUCCESS   12561        28     5011      3664
10          durbin  SUCCESS    4916        14     2075      3101
11         fdtd-2d  SUCCESS   36041        23     3539      4699
12  floyd-warshall  SUCCESS  432003         0      251       601
13            gemm  SUCCESS   19641       181    11798     12614
14          gemver  SUCCESS    4542        50    20414     11856
15         gesummv  SUCCESS     629        70    15724      9093
16     gramschmidt  SUCCESS   64006        14     5565      5594
17         heat-3d  SUCCESS   83621        20     3655      4539
18       jacobi-1d  SUCCESS    1243        34     5305      5461
19       jacobi-2d  SUCCESS   95181        17     2236      2956
20              lu  SUCCESS  149921        14     1804      2201
21          ludcmp  SUCCESS  128041        14     1914      2627
22             mvt  SUCCESS    2028        28    13996      6931
23        nussinov  SUCCESS   84551         0      460      1051
24       seidel-2d  SUCCESS  109835       145    43451     28873
25            symm  SUCCESS   29341        25     2409      3117
26           syr2k  SUCCESS   57256        14     1934      1853
27            syrk  SUCCESS   57046        14     1613      1771
28         trisolv  SUCCESS    4601        14     1232      1414
29            trmm  SUCCESS    None      None     None      None

   BRAM_18K_usage URAM_usage DSP_avail FF_avail LUT_avail BRAM_18K_avail  \
0               0          0      4272   850560    425280           2160
1               0          0      4272   850560    425280           2160
2               0          0      4272   850560    425280           2160
3               0          0      4272   850560    425280           2160
4               0          0      4272   850560    425280           2160
5               0          0      4272   850560    425280           2160
6               0          0      4272   850560    425280           2160
7               0          0      4272   850560    425280           2160
8            None       None      None     None      None           None
9               0          0      4272   850560    425280           2160
10              2          0      4272   850560    425280           2160
11              0          0      4272   850560    425280           2160
12              0          0      4272   850560    425280           2160
13              0          0      4272   850560    425280           2160
14              0          0      4272   850560    425280           2160
15              0          0      4272   850560    425280           2160
16              0          0      4272   850560    425280           2160
17              0          0      4272   850560    425280           2160
18              0          0      4272   850560    425280           2160
19              0          0      4272   850560    425280           2160
20              0          0      4272   850560    425280           2160
21              0          0      4272   850560    425280           2160
22              0          0      4272   850560    425280           2160
23              0          0      4272   850560    425280           2160
24              0          0      4272   850560    425280           2160
25              0          0      4272   850560    425280           2160
26              0          0      4272   850560    425280           2160
27              0          0      4272   850560    425280           2160
28              0          0      4272   850560    425280           2160
29           None       None      None     None      None           None

   URAM_avail
0          80
1          80
2          80
3          80
4          80
5          80
6          80
7          80
8        None
9          80
10         80
11         80
12         80
13         80
14         80
15         80
16         80
17         80
18         80
19         80
20         80
21         80
22         80
23         80
24         80
25         80
26         80
27         80
28         80
29       None

## Results

Here we list all the results as a table.

In [9]:
baseline = pb_flow.to_pandas(pb_flow.process_pb_flow_result_dir(options['baseline'].work_dir, options['baseline']))
baseline

,name,status,latency,DSP_usage,FF_usage,LUT_usage,BRAM_18K_usage,URAM_usage,DSP_avail,FF_avail,LUT_avail,BRAM_18K_avail,URAM_avail
0,2mm,SUCCESS,6830,50,9999,6720,0,0,4272,850560,425280,2160,80
1,3mm,SUCCESS,11113,30,6792,6466,0,0,4272,850560,425280,2160,80
2,adi,SUCCESS,51181,53,18421,13623,0,0,4272,850560,425280,2160,80
3,atax,SUCCESS,1928,595,52231,43267,0,0,4272,850560,425280,2160,80
4,bicg,SUCCESS,2596,39,13630,6473,0,0,4272,850560,425280,2160,80
5,cholesky,SUCCESS,137534,14,1614,2279,0,0,4272,850560,425280,2160,80
6,correlation,SUCCESS,12927,34,12033,10260,0,0,4272,850560,425280,2160,80
7,covariance,SUCCESS,13455,28,10179,6731,0,0,4272,850560,425280,2160,80
8,deriche,SUCCESS,None,None,None,None,None,None,None,None,None,None,None
9,doitgen,SUCCESS,12561,28,5011,3664,0,0,4272,850560,425280,2160,80
10,durbin,SUCCESS,4916,14,2075,3101,2,0,4272,850560,425280,2160,80
11,fdtd-2d,SUCCESS,36041,23,3539,4699,0,0,4272,850560,425280,2160,80
12,floyd-warshall,SUCCESS,432003,0,251,601,0,0,4272,850560,425280,2160,80
13,gemm,SUCCESS,19641,181,11798,12614,0,0,4272,850560,425280,2160,80
14,gemver,SUCCESS,4542,50,20414,11856,0,0,4272,850560,425280,2160,80
15,gesummv,SUCCESS,629,70,15724,9093,0,0,4272,850560,425280,2160,80
16,gramschmidt,SUCCESS,64006,14,5565,5594,0,0,4272,850560,425280,2160,80
17,heat-3d,SUCCESS,83621,20,3655,4539,0,0,4272,850560,425280,2160,80
18,jacobi-1d,SUCCESS,1243,34,5305,5461,0,0,4272,850560,425280,2160,80
19,jacobi-2d,SUCCESS,95181,17,2236,2956,0,0,4272,850560,425280,2160,80
20,lu,SUCCESS,149921,14,1804,2201,0,0,4272,850560,425280,2160,80
21,ludcmp,SUCCESS,128041,14,1914,2627,0,0,4272,850560,425280,2160,80
22,mvt,SUCCESS,2028,28,13996,6931,0,0,4272,850560,425280,2160,80
23,nussinov,SUCCESS,84551,0,460,1051,0,0,4272,850560,425280,2160,80
24,seidel-2d,SUCCESS,109835,145,43451,28873,0,0,4272,850560,425280,2160,80
25,symm,SUCCESS,29341,25,2409,3117,0,0,4272,850560,425280,2160,80
26,syr2k,SUCCESS,57256,14,1934,1853,0,0,4272,850560,425280,2160,80
27,syrk,SUCCESS,57046,14,1613,1771,0,0,4272,850560,425280,2160,80
28,trisolv,SUCCESS,4601,14,1232,1414,0,0,4272,850560,425280,2160,80
29,trmm,SUCCESS,None,None,None,None,None,None,None,None,None,None,None